### PR TITLE
Apply PR 'make tests run with rdflib 4'

### PR DESCRIPTION
**Pull request by ysangkok**
The pull request below wasn't merged when you forked. I rebased it on top of your changes.

https://bitbucket.org/ww/telescope/pull-requests/1/make-tests-run-with-rdflib-4/diff

### CODE REVIEW

**Comment by pudo** [comment]
Whoooa if that PR does what it says I owe you lots of beer. Has development of telescope continued?

**Comment by ysangkok** [comment]
No, this is just a single PR I made to ww's branch in 2013. I am not the maintainer of any library. Also, there is still one single test failing, maybe I'll fix that later.

**Comment by ysangkok** [comment]
This is the failing test:

```
======================================================================
FAIL: tests.test_compiler.TestCompilingSelect.test_compiling_select_all_outputs_asterisk
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/janus/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/sparqlquery/tests/test_compiler.py", line 321, in test_compiling_select_all_outputs_asterisk
    self.compiler.compile(select), self.PREFIXES, 'SELECT * WHERE { }'
  File "/tmp/sparqlquery/tests/test_compiler.py", line 29, in tokens_equal
    assert_equal(output, expected)
AssertionError: u'PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> SELECT ?* WHERE { }' != 'PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> SELECT * WHERE { }'
```

Before this PR, 21 tests were failing. The test was failing before too, but in a different way:

```
======================================================================
FAIL: tests.test_compiler.TestCompilingSelect.test_compiling_select_all_outputs_asterisk
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/janus/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/sparqlquery/tests/test_compiler.py", line 321, in test_compiling_select_all_outputs_asterisk
    self.compiler.compile(select), self.PREFIXES, 'SELECT * WHERE { }'
  File "/tmp/sparqlquery/tests/test_compiler.py", line 29, in tokens_equal
    assert_equal(output, expected)
AssertionError: u'PREFIX foaf: http://xmlns.com/foaf/0.1/ PREFIX rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns# SELECT * WHERE { }' != 'PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> SELECT * WHERE { }'
```

**Comment by ysangkok** [comment]
Great, thanks!

**Pull request merged**
