### PR TITLE
Update queries

### PR DESCRIPTION
**Pull request by flagist0**
Hi!
Here is a basic implementation of graph update part of SPARQL Update (https://www.w3.org/TR/sparql11-update/#graphUpdate).
Also it contains small fix for select query generation: currently in master period is generated on separate line, making the query less readable.

### CODE REVIEW

**Comment by pudo** [comment]
Hey I'm sorry about not reacting sooner. Your code looks pretty solid. Do you want commit rights on the repo?

**Comment by flagist0** [comment]
Thank you, Friedrich! Having commit rights would be very nice, cause I'm planning to implement some missing parts of SPARQL queries and it would simplify the process

**Comment by pudo** [comment]
There you go. Let me know if you plan to maintain this actively, happy to give it to a more active caretaker!

**Comment by flagist0** [comment]
Friedrich, sorry for spending your time with these pull requests, I forgot that you gave me commit rights.

**Pull request merged**
